# Generated by Django 4.1.1 on 2024-05-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randfoof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='restaurent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='randfoof.restaurent'),
        ),
    ]
