# Generated by Django 4.1.1 on 2024-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randfoof', '0002_alter_dish_restaurent'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='picture',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
