# Generated by Django 4.1.1 on 2024-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randfoof', '0004_alter_restaurent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='picture',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
